// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2iG2AfZowPZ62eGNAqhfGZ26j9IDBHk',
    appId: '1:953919045825:web:dcdc08db39d08ea225d440',
    messagingSenderId: '953919045825',
    projectId: 'fitness-appen-future',
    authDomain: 'fitness-appen-future.firebaseapp.com',
    databaseURL: 'https://fitness-appen-future-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitness-appen-future.appspot.com',
    measurementId: 'G-N4244V9GQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByB41W89m9VpgZs-uvEpPVxpAxmgzLxA0',
    appId: '1:953919045825:android:9e7073838d090fa725d440',
    messagingSenderId: '953919045825',
    projectId: 'fitness-appen-future',
    databaseURL: 'https://fitness-appen-future-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitness-appen-future.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWn3vH5TTOqMHrlW4xdwVbgmRri0gwkPE',
    appId: '1:953919045825:ios:826e626628407d5925d440',
    messagingSenderId: '953919045825',
    projectId: 'fitness-appen-future',
    databaseURL: 'https://fitness-appen-future-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitness-appen-future.appspot.com',
    iosClientId: '953919045825-ptl2ucqfj4rn1049h0pojubhljbl1798.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessBodyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWn3vH5TTOqMHrlW4xdwVbgmRri0gwkPE',
    appId: '1:953919045825:ios:826e626628407d5925d440',
    messagingSenderId: '953919045825',
    projectId: 'fitness-appen-future',
    databaseURL: 'https://fitness-appen-future-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitness-appen-future.appspot.com',
    iosClientId: '953919045825-ptl2ucqfj4rn1049h0pojubhljbl1798.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessBodyApp',
  );
}
